# Generated by Django 5.2.16 on 2026-08-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_orders(apps, schema_editor):
    Customer = apps.get_model("shop", "Customer")
    Order = apps.get_model("shop", "Order")

    for order in Order.objects.order_by("id"):
        customer, _ = Customer.objects.get_or_create(
            email=order.email,
            phone=order.phone,
            defaults={
                "name": order.customer_name,
                "address": order.address,
                "user_id": order.customer_id,
            },
        )
        Order.objects.filter(id=order.id).update(customer_profile_id=customer.id)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_specifications_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.customer'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('email', 'phone'), name='unique_customer_contact'),
        ),
        migrations.RunPython(link_existing_orders, migrations.RunPython.noop),
    ]
